# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0016_auto_20160201_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='priorityArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userportal.PriorityArea', verbose_name=b'Priority Area'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='serviceunits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountCreatedEmailOn',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Account Created Email On'),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountCreatedOn',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Account Created On'),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountEmailHash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Account Email Hash'),
        ),
        migrations.AlterField(
            model_name='person',
            name='accountEmailOn',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Account Creation Email On'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=32, verbose_name=b'First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institutionEmail',
            field=models.EmailField(max_length=64, verbose_name=b'Institution Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferredEmail',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name=b'Alternative Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='principalInvestigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='userportal.Person', verbose_name=b'Principal Investigator'),
        ),
    ]
