# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0018_auto_20160217_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userportal.Project')),
            ],
        ),
    ]
