# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0019_researchclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(help_text=b'Allocation that this applies to', on_delete=django.db.models.deletion.CASCADE, to='userportal.Allocation')),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of the partition (exactly as on system)', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='filesystem',
            name='name',
            field=models.CharField(help_text=b'Name of the filesystem (exactly as on system)', max_length=32),
        ),
        migrations.AddField(
            model_name='allocationpartition',
            name='partition',
            field=models.ForeignKey(help_text=b'Partition that this applies to', on_delete=django.db.models.deletion.CASCADE, to='userportal.Partition'),
        ),
    ]
