# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0020_auto_20160314_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamlDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaults', models.TextField(blank=True, help_text=b'YAML File defaults in correct YAML format for activate account. The last one will be used.', null=True)),
            ],
        ),
    ]
