# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0021_yamldefaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamldefaults',
            options={'verbose_name_plural': 'Yaml defaults'},
        ),
    ]
