# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0022_auto_20160316_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='detailsFilledOn',
            field=models.DateTimeField(blank=True, help_text=b'The data that the person filled their details on for account creation', null=True, verbose_name=b'Details Filled On'),
        ),
    ]
