# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0023_person_detailsfilledon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='altAdmins',
            field=models.ManyToManyField(help_text=b'Alternative Administrators for the project that can request changes', related_name='admin_people', to='userportal.Person', verbose_name=b'Alternative Administrators'),
        ),
        migrations.AlterField(
            model_name='person',
            name='detailsFilledOn',
            field=models.DateTimeField(blank=True, help_text=b'The date that the person filled their details on for account creation', null=True, verbose_name=b'Details Filled On'),
        ),
    ]
