# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0024_auto_20160527_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaccount',
            name='passwordHash',
        ),
    ]
